# Application name and labels
app:
  name: crud-app
  labels:
    app: crud-app

# Image configuration
image:
  repository: samuvel/crud-app
  tag: "null-90"
  pullPolicy: IfNotPresent

# Kubernetes deployment configuration
deployment:
  replicas: 2  # Number of replicas
  podAnnotations: {}
  podLabels: {}
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# Job configuration
createTestConnectionJob: false  

# Service configuration
service:
  type: LoadBalancer  # Can be ClusterIP, NodePort, or LoadBalancer
  port: 80
  targetPort: 5000
  # nodePort: 30001  # Commented out since ClusterIP is used, only required for NodePort

# ServiceAccount configuration
serviceAccount:
  create: true   
  name: "crud-app"  

# Ingress configuration
ingress:
  enabled: false  
  annotations: {}
  hosts:
    - host: crud-app.example.com  
      paths:
        - /
  tls: []  # Configure TLS if needed, otherwise leave empty

# Horizontal Pod Autoscaler (HPA) configuration
autoscaling:
  enabled: false  # Set to true if HPA is needed
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80  # Target CPU percentage for scaling

# Volume mounts (if needed for persistence)
volumes: []
volumeMounts: []
